// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: db.proto

package dbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserRequest) Reset() {
	*x = UpsertUserRequest{}
	mi := &file_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserRequest) ProtoMessage() {}

func (x *UpsertUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserRequest.ProtoReflect.Descriptor instead.
func (*UpsertUserRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpsertUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpsertUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUserReply) Reset() {
	*x = UpsertUserReply{}
	mi := &file_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUserReply) ProtoMessage() {}

func (x *UpsertUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUserReply.ProtoReflect.Descriptor instead.
func (*UpsertUserReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertUserReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersReply) Reset() {
	*x = ListUsersReply{}
	mi := &file_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersReply) ProtoMessage() {}

func (x *ListUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersReply.ProtoReflect.Descriptor instead.
func (*ListUsersReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersReply) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatSessionRequest) Reset() {
	*x = CreateChatSessionRequest{}
	mi := &file_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatSessionRequest) ProtoMessage() {}

func (x *CreateChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{5}
}

func (x *CreateChatSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateChatSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateChatSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateChatSessionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatSessionReply) Reset() {
	*x = CreateChatSessionReply{}
	mi := &file_db_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatSessionReply) ProtoMessage() {}

func (x *CreateChatSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatSessionReply.ProtoReflect.Descriptor instead.
func (*CreateChatSessionReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{6}
}

func (x *CreateChatSessionReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ChatSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Pinned        bool                   `protobuf:"varint,3,opt,name=pinned,proto3" json:"pinned,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSession) Reset() {
	*x = ChatSession{}
	mi := &file_db_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSession) ProtoMessage() {}

func (x *ChatSession) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSession.ProtoReflect.Descriptor instead.
func (*ChatSession) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{7}
}

func (x *ChatSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatSession) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChatSession) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ChatSession) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListChatSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatSessionsRequest) Reset() {
	*x = ListChatSessionsRequest{}
	mi := &file_db_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionsRequest) ProtoMessage() {}

func (x *ListChatSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListChatSessionsRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{8}
}

func (x *ListChatSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListChatSessionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ChatSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatSessionsReply) Reset() {
	*x = ListChatSessionsReply{}
	mi := &file_db_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatSessionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionsReply) ProtoMessage() {}

func (x *ListChatSessionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionsReply.ProtoReflect.Descriptor instead.
func (*ListChatSessionsReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{9}
}

func (x *ListChatSessionsReply) GetSessions() []*ChatSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type RenameChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameChatSessionRequest) Reset() {
	*x = RenameChatSessionRequest{}
	mi := &file_db_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameChatSessionRequest) ProtoMessage() {}

func (x *RenameChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameChatSessionRequest.ProtoReflect.Descriptor instead.
func (*RenameChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{10}
}

func (x *RenameChatSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenameChatSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RenameChatSessionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type RenameChatSessionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameChatSessionReply) Reset() {
	*x = RenameChatSessionReply{}
	mi := &file_db_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameChatSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameChatSessionReply) ProtoMessage() {}

func (x *RenameChatSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameChatSessionReply.ProtoReflect.Descriptor instead.
func (*RenameChatSessionReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{11}
}

func (x *RenameChatSessionReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatSessionRequest) Reset() {
	*x = DeleteChatSessionRequest{}
	mi := &file_db_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatSessionRequest) ProtoMessage() {}

func (x *DeleteChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteChatSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteChatSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteChatSessionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatSessionReply) Reset() {
	*x = DeleteChatSessionReply{}
	mi := &file_db_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatSessionReply) ProtoMessage() {}

func (x *DeleteChatSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatSessionReply.ProtoReflect.Descriptor instead.
func (*DeleteChatSessionReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteChatSessionReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // user | assistant
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_db_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{14}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AppendChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendChatMessageRequest) Reset() {
	*x = AppendChatMessageRequest{}
	mi := &file_db_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendChatMessageRequest) ProtoMessage() {}

func (x *AppendChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendChatMessageRequest.ProtoReflect.Descriptor instead.
func (*AppendChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{15}
}

func (x *AppendChatMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AppendChatMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppendChatMessageRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AppendChatMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AppendChatMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendChatMessageReply) Reset() {
	*x = AppendChatMessageReply{}
	mi := &file_db_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendChatMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendChatMessageReply) ProtoMessage() {}

func (x *AppendChatMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendChatMessageReply.ProtoReflect.Descriptor instead.
func (*AppendChatMessageReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{16}
}

func (x *AppendChatMessageReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListChatMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMessagesRequest) Reset() {
	*x = ListChatMessagesRequest{}
	mi := &file_db_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessagesRequest) ProtoMessage() {}

func (x *ListChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{17}
}

func (x *ListChatMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListChatMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListChatMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListChatMessagesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMessagesReply) Reset() {
	*x = ListChatMessagesReply{}
	mi := &file_db_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessagesReply) ProtoMessage() {}

func (x *ListChatMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessagesReply.ProtoReflect.Descriptor instead.
func (*ListChatMessagesReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{18}
}

func (x *ListChatMessagesReply) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type FirmsPoint struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid; caller-supplied so re-ingestion is idempotent
	Latitude         float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AcqDate          string                 `protobuf:"bytes,4,opt,name=acq_date,json=acqDate,proto3" json:"acq_date,omitempty"` // YYYY-MM-DD
	AcqTime          string                 `protobuf:"bytes,5,opt,name=acq_time,json=acqTime,proto3" json:"acq_time,omitempty"` // HH:MM:SS, optional ("" if unknown)
	BrightTi4        float64                `protobuf:"fixed64,6,opt,name=bright_ti4,json=brightTi4,proto3" json:"bright_ti4,omitempty"`
	BrightTi5        float64                `protobuf:"fixed64,7,opt,name=bright_ti5,json=brightTi5,proto3" json:"bright_ti5,omitempty"`
	Frp              float64                `protobuf:"fixed64,8,opt,name=frp,proto3" json:"frp,omitempty"`
	Confidence       string                 `protobuf:"bytes,9,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Satellite        string                 `protobuf:"bytes,10,opt,name=satellite,proto3" json:"satellite,omitempty"`
	BrightT31        float64                `protobuf:"fixed64,11,opt,name=bright_t31,json=brightT31,proto3" json:"bright_t31,omitempty"`
	Scan             float64                `protobuf:"fixed64,12,opt,name=scan,proto3" json:"scan,omitempty"`
	Track            float64                `protobuf:"fixed64,13,opt,name=track,proto3" json:"track,omitempty"`
	Landcover        int32                  `protobuf:"varint,14,opt,name=landcover,proto3" json:"landcover,omitempty"` // ESA WorldCover class code, 0 = unknown
	DistIndustrialM  float64                `protobuf:"fixed64,15,opt,name=dist_industrial_m,json=distIndustrialM,proto3" json:"dist_industrial_m,omitempty"`
	InsideIndustrial bool                   `protobuf:"varint,16,opt,name=inside_industrial,json=insideIndustrial,proto3" json:"inside_industrial,omitempty"`
	OsmId            int64                  `protobuf:"varint,17,opt,name=osm_id,json=osmId,proto3" json:"osm_id,omitempty"` // nearest industrial_sites.osm_id, 0 = none
	PersistenceScore float64                `protobuf:"fixed64,18,opt,name=persistence_score,json=persistenceScore,proto3" json:"persistence_score,omitempty"`
	PredictedClass   string                 `protobuf:"bytes,19,opt,name=predicted_class,json=predictedClass,proto3" json:"predicted_class,omitempty"` // industrial_flare | thermal_power | mining | forest | agriculture | unknown
	IndustrialProb   float64                `protobuf:"fixed64,20,opt,name=industrial_prob,json=industrialProb,proto3" json:"industrial_prob,omitempty"`
	ClusterId        string                 `protobuf:"bytes,21,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"` // uuid, "" if unclustered
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FirmsPoint) Reset() {
	*x = FirmsPoint{}
	mi := &file_db_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmsPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmsPoint) ProtoMessage() {}

func (x *FirmsPoint) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmsPoint.ProtoReflect.Descriptor instead.
func (*FirmsPoint) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{19}
}

func (x *FirmsPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FirmsPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *FirmsPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *FirmsPoint) GetAcqDate() string {
	if x != nil {
		return x.AcqDate
	}
	return ""
}

func (x *FirmsPoint) GetAcqTime() string {
	if x != nil {
		return x.AcqTime
	}
	return ""
}

func (x *FirmsPoint) GetBrightTi4() float64 {
	if x != nil {
		return x.BrightTi4
	}
	return 0
}

func (x *FirmsPoint) GetBrightTi5() float64 {
	if x != nil {
		return x.BrightTi5
	}
	return 0
}

func (x *FirmsPoint) GetFrp() float64 {
	if x != nil {
		return x.Frp
	}
	return 0
}

func (x *FirmsPoint) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *FirmsPoint) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *FirmsPoint) GetBrightT31() float64 {
	if x != nil {
		return x.BrightT31
	}
	return 0
}

func (x *FirmsPoint) GetScan() float64 {
	if x != nil {
		return x.Scan
	}
	return 0
}

func (x *FirmsPoint) GetTrack() float64 {
	if x != nil {
		return x.Track
	}
	return 0
}

func (x *FirmsPoint) GetLandcover() int32 {
	if x != nil {
		return x.Landcover
	}
	return 0
}

func (x *FirmsPoint) GetDistIndustrialM() float64 {
	if x != nil {
		return x.DistIndustrialM
	}
	return 0
}

func (x *FirmsPoint) GetInsideIndustrial() bool {
	if x != nil {
		return x.InsideIndustrial
	}
	return false
}

func (x *FirmsPoint) GetOsmId() int64 {
	if x != nil {
		return x.OsmId
	}
	return 0
}

func (x *FirmsPoint) GetPersistenceScore() float64 {
	if x != nil {
		return x.PersistenceScore
	}
	return 0
}

func (x *FirmsPoint) GetPredictedClass() string {
	if x != nil {
		return x.PredictedClass
	}
	return ""
}

func (x *FirmsPoint) GetIndustrialProb() float64 {
	if x != nil {
		return x.IndustrialProb
	}
	return 0
}

func (x *FirmsPoint) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type UpsertFirmsPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *FirmsPoint            `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertFirmsPointRequest) Reset() {
	*x = UpsertFirmsPointRequest{}
	mi := &file_db_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFirmsPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFirmsPointRequest) ProtoMessage() {}

func (x *UpsertFirmsPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFirmsPointRequest.ProtoReflect.Descriptor instead.
func (*UpsertFirmsPointRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{20}
}

func (x *UpsertFirmsPointRequest) GetPoint() *FirmsPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type UpsertFirmsPointReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertFirmsPointReply) Reset() {
	*x = UpsertFirmsPointReply{}
	mi := &file_db_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFirmsPointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFirmsPointReply) ProtoMessage() {}

func (x *UpsertFirmsPointReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFirmsPointReply.ProtoReflect.Descriptor instead.
func (*UpsertFirmsPointReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{21}
}

func (x *UpsertFirmsPointReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFirmsPointsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MinLat         float64                `protobuf:"fixed64,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLon         float64                `protobuf:"fixed64,2,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	MaxLat         float64                `protobuf:"fixed64,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLon         float64                `protobuf:"fixed64,4,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	DateFrom       string                 `protobuf:"bytes,5,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`                   // YYYY-MM-DD, "" = no lower bound
	DateTo         string                 `protobuf:"bytes,6,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`                         // YYYY-MM-DD, "" = no upper bound
	PredictedClass string                 `protobuf:"bytes,7,opt,name=predicted_class,json=predictedClass,proto3" json:"predicted_class,omitempty"` // "" = all classes
	Limit          int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`                                        // 0 = server default (500), clamped to 5000
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListFirmsPointsRequest) Reset() {
	*x = ListFirmsPointsRequest{}
	mi := &file_db_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFirmsPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFirmsPointsRequest) ProtoMessage() {}

func (x *ListFirmsPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFirmsPointsRequest.ProtoReflect.Descriptor instead.
func (*ListFirmsPointsRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{22}
}

func (x *ListFirmsPointsRequest) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *ListFirmsPointsRequest) GetMinLon() float64 {
	if x != nil {
		return x.MinLon
	}
	return 0
}

func (x *ListFirmsPointsRequest) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *ListFirmsPointsRequest) GetMaxLon() float64 {
	if x != nil {
		return x.MaxLon
	}
	return 0
}

func (x *ListFirmsPointsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *ListFirmsPointsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *ListFirmsPointsRequest) GetPredictedClass() string {
	if x != nil {
		return x.PredictedClass
	}
	return ""
}

func (x *ListFirmsPointsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListFirmsPointsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*FirmsPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFirmsPointsReply) Reset() {
	*x = ListFirmsPointsReply{}
	mi := &file_db_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFirmsPointsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFirmsPointsReply) ProtoMessage() {}

func (x *ListFirmsPointsReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFirmsPointsReply.ProtoReflect.Descriptor instead.
func (*ListFirmsPointsReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{23}
}

func (x *ListFirmsPointsReply) GetPoints() []*FirmsPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type UpdateFirmsPointClassificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PredictedClass   string                 `protobuf:"bytes,2,opt,name=predicted_class,json=predictedClass,proto3" json:"predicted_class,omitempty"`
	IndustrialProb   float64                `protobuf:"fixed64,3,opt,name=industrial_prob,json=industrialProb,proto3" json:"industrial_prob,omitempty"`
	PersistenceScore float64                `protobuf:"fixed64,4,opt,name=persistence_score,json=persistenceScore,proto3" json:"persistence_score,omitempty"`
	DistIndustrialM  float64                `protobuf:"fixed64,5,opt,name=dist_industrial_m,json=distIndustrialM,proto3" json:"dist_industrial_m,omitempty"`
	InsideIndustrial bool                   `protobuf:"varint,6,opt,name=inside_industrial,json=insideIndustrial,proto3" json:"inside_industrial,omitempty"`
	Landcover        int32                  `protobuf:"varint,7,opt,name=landcover,proto3" json:"landcover,omitempty"`
	ClusterId        string                 `protobuf:"bytes,8,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"` // "" = leave unchanged
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateFirmsPointClassificationRequest) Reset() {
	*x = UpdateFirmsPointClassificationRequest{}
	mi := &file_db_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFirmsPointClassificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFirmsPointClassificationRequest) ProtoMessage() {}

func (x *UpdateFirmsPointClassificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFirmsPointClassificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateFirmsPointClassificationRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateFirmsPointClassificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFirmsPointClassificationRequest) GetPredictedClass() string {
	if x != nil {
		return x.PredictedClass
	}
	return ""
}

func (x *UpdateFirmsPointClassificationRequest) GetIndustrialProb() float64 {
	if x != nil {
		return x.IndustrialProb
	}
	return 0
}

func (x *UpdateFirmsPointClassificationRequest) GetPersistenceScore() float64 {
	if x != nil {
		return x.PersistenceScore
	}
	return 0
}

func (x *UpdateFirmsPointClassificationRequest) GetDistIndustrialM() float64 {
	if x != nil {
		return x.DistIndustrialM
	}
	return 0
}

func (x *UpdateFirmsPointClassificationRequest) GetInsideIndustrial() bool {
	if x != nil {
		return x.InsideIndustrial
	}
	return false
}

func (x *UpdateFirmsPointClassificationRequest) GetLandcover() int32 {
	if x != nil {
		return x.Landcover
	}
	return 0
}

func (x *UpdateFirmsPointClassificationRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type UpdateFirmsPointClassificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFirmsPointClassificationReply) Reset() {
	*x = UpdateFirmsPointClassificationReply{}
	mi := &file_db_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFirmsPointClassificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFirmsPointClassificationReply) ProtoMessage() {}

func (x *UpdateFirmsPointClassificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFirmsPointClassificationReply.ProtoReflect.Descriptor instead.
func (*UpdateFirmsPointClassificationReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateFirmsPointClassificationReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ThermalCluster struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CentroidLat    float64                `protobuf:"fixed64,2,opt,name=centroid_lat,json=centroidLat,proto3" json:"centroid_lat,omitempty"`
	CentroidLon    float64                `protobuf:"fixed64,3,opt,name=centroid_lon,json=centroidLon,proto3" json:"centroid_lon,omitempty"`
	Count          int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	AvgFrp         float64                `protobuf:"fixed64,5,opt,name=avg_frp,json=avgFrp,proto3" json:"avg_frp,omitempty"`
	MaxFrp         float64                `protobuf:"fixed64,6,opt,name=max_frp,json=maxFrp,proto3" json:"max_frp,omitempty"`
	Persistence    float64                `protobuf:"fixed64,7,opt,name=persistence,proto3" json:"persistence,omitempty"`
	FirstSeen      string                 `protobuf:"bytes,8,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"` // YYYY-MM-DD
	LastSeen       string                 `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`    // YYYY-MM-DD
	PredictedClass string                 `protobuf:"bytes,10,opt,name=predicted_class,json=predictedClass,proto3" json:"predicted_class,omitempty"`
	OsmId          int64                  `protobuf:"varint,11,opt,name=osm_id,json=osmId,proto3" json:"osm_id,omitempty"` // 0 = none
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThermalCluster) Reset() {
	*x = ThermalCluster{}
	mi := &file_db_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThermalCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThermalCluster) ProtoMessage() {}

func (x *ThermalCluster) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThermalCluster.ProtoReflect.Descriptor instead.
func (*ThermalCluster) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{26}
}

func (x *ThermalCluster) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ThermalCluster) GetCentroidLat() float64 {
	if x != nil {
		return x.CentroidLat
	}
	return 0
}

func (x *ThermalCluster) GetCentroidLon() float64 {
	if x != nil {
		return x.CentroidLon
	}
	return 0
}

func (x *ThermalCluster) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ThermalCluster) GetAvgFrp() float64 {
	if x != nil {
		return x.AvgFrp
	}
	return 0
}

func (x *ThermalCluster) GetMaxFrp() float64 {
	if x != nil {
		return x.MaxFrp
	}
	return 0
}

func (x *ThermalCluster) GetPersistence() float64 {
	if x != nil {
		return x.Persistence
	}
	return 0
}

func (x *ThermalCluster) GetFirstSeen() string {
	if x != nil {
		return x.FirstSeen
	}
	return ""
}

func (x *ThermalCluster) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *ThermalCluster) GetPredictedClass() string {
	if x != nil {
		return x.PredictedClass
	}
	return ""
}

func (x *ThermalCluster) GetOsmId() int64 {
	if x != nil {
		return x.OsmId
	}
	return 0
}

type UpsertThermalClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       *ThermalCluster        `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertThermalClusterRequest) Reset() {
	*x = UpsertThermalClusterRequest{}
	mi := &file_db_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertThermalClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertThermalClusterRequest) ProtoMessage() {}

func (x *UpsertThermalClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertThermalClusterRequest.ProtoReflect.Descriptor instead.
func (*UpsertThermalClusterRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{27}
}

func (x *UpsertThermalClusterRequest) GetCluster() *ThermalCluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type UpsertThermalClusterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertThermalClusterReply) Reset() {
	*x = UpsertThermalClusterReply{}
	mi := &file_db_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertThermalClusterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertThermalClusterReply) ProtoMessage() {}

func (x *UpsertThermalClusterReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertThermalClusterReply.ProtoReflect.Descriptor instead.
func (*UpsertThermalClusterReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{28}
}

func (x *UpsertThermalClusterReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListThermalClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLat        float64                `protobuf:"fixed64,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLon        float64                `protobuf:"fixed64,2,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	MaxLat        float64                `protobuf:"fixed64,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLon        float64                `protobuf:"fixed64,4,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThermalClustersRequest) Reset() {
	*x = ListThermalClustersRequest{}
	mi := &file_db_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThermalClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThermalClustersRequest) ProtoMessage() {}

func (x *ListThermalClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThermalClustersRequest.ProtoReflect.Descriptor instead.
func (*ListThermalClustersRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{29}
}

func (x *ListThermalClustersRequest) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *ListThermalClustersRequest) GetMinLon() float64 {
	if x != nil {
		return x.MinLon
	}
	return 0
}

func (x *ListThermalClustersRequest) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *ListThermalClustersRequest) GetMaxLon() float64 {
	if x != nil {
		return x.MaxLon
	}
	return 0
}

type ListThermalClustersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*ThermalCluster      `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListThermalClustersReply) Reset() {
	*x = ListThermalClustersReply{}
	mi := &file_db_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListThermalClustersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListThermalClustersReply) ProtoMessage() {}

func (x *ListThermalClustersReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListThermalClustersReply.ProtoReflect.Descriptor instead.
func (*ListThermalClustersReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{30}
}

func (x *ListThermalClustersReply) GetClusters() []*ThermalCluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type UpsertIndustrialSiteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OsmId          int64                  `protobuf:"varint,1,opt,name=osm_id,json=osmId,proto3" json:"osm_id,omitempty"`
	CentroidLat    float64                `protobuf:"fixed64,2,opt,name=centroid_lat,json=centroidLat,proto3" json:"centroid_lat,omitempty"`
	CentroidLon    float64                `protobuf:"fixed64,3,opt,name=centroid_lon,json=centroidLon,proto3" json:"centroid_lon,omitempty"`
	IndustrialType string                 `protobuf:"bytes,4,opt,name=industrial_type,json=industrialType,proto3" json:"industrial_type,omitempty"` // refinery | power_plant | steel | mining | lng | other
	Name           string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	TagsJson       string                 `protobuf:"bytes,6,opt,name=tags_json,json=tagsJson,proto3" json:"tags_json,omitempty"` // raw JSON object as text, stored into JSONB; "" = null
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertIndustrialSiteRequest) Reset() {
	*x = UpsertIndustrialSiteRequest{}
	mi := &file_db_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertIndustrialSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertIndustrialSiteRequest) ProtoMessage() {}

func (x *UpsertIndustrialSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertIndustrialSiteRequest.ProtoReflect.Descriptor instead.
func (*UpsertIndustrialSiteRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{31}
}

func (x *UpsertIndustrialSiteRequest) GetOsmId() int64 {
	if x != nil {
		return x.OsmId
	}
	return 0
}

func (x *UpsertIndustrialSiteRequest) GetCentroidLat() float64 {
	if x != nil {
		return x.CentroidLat
	}
	return 0
}

func (x *UpsertIndustrialSiteRequest) GetCentroidLon() float64 {
	if x != nil {
		return x.CentroidLon
	}
	return 0
}

func (x *UpsertIndustrialSiteRequest) GetIndustrialType() string {
	if x != nil {
		return x.IndustrialType
	}
	return ""
}

func (x *UpsertIndustrialSiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertIndustrialSiteRequest) GetTagsJson() string {
	if x != nil {
		return x.TagsJson
	}
	return ""
}

type UpsertIndustrialSiteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertIndustrialSiteReply) Reset() {
	*x = UpsertIndustrialSiteReply{}
	mi := &file_db_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertIndustrialSiteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertIndustrialSiteReply) ProtoMessage() {}

func (x *UpsertIndustrialSiteReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertIndustrialSiteReply.ProtoReflect.Descriptor instead.
func (*UpsertIndustrialSiteReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{32}
}

func (x *UpsertIndustrialSiteReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type NearestIndustrialSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearestIndustrialSiteRequest) Reset() {
	*x = NearestIndustrialSiteRequest{}
	mi := &file_db_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearestIndustrialSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearestIndustrialSiteRequest) ProtoMessage() {}

func (x *NearestIndustrialSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearestIndustrialSiteRequest.ProtoReflect.Descriptor instead.
func (*NearestIndustrialSiteRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{33}
}

func (x *NearestIndustrialSiteRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NearestIndustrialSiteRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type NearestIndustrialSiteReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Found          bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	OsmId          int64                  `protobuf:"varint,2,opt,name=osm_id,json=osmId,proto3" json:"osm_id,omitempty"`
	DistM          float64                `protobuf:"fixed64,3,opt,name=dist_m,json=distM,proto3" json:"dist_m,omitempty"`
	Inside         bool                   `protobuf:"varint,4,opt,name=inside,proto3" json:"inside,omitempty"` // v1: dist_m < 50, no polygon containment test yet
	IndustrialType string                 `protobuf:"bytes,5,opt,name=industrial_type,json=industrialType,proto3" json:"industrial_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NearestIndustrialSiteReply) Reset() {
	*x = NearestIndustrialSiteReply{}
	mi := &file_db_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearestIndustrialSiteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearestIndustrialSiteReply) ProtoMessage() {}

func (x *NearestIndustrialSiteReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearestIndustrialSiteReply.ProtoReflect.Descriptor instead.
func (*NearestIndustrialSiteReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{34}
}

func (x *NearestIndustrialSiteReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *NearestIndustrialSiteReply) GetOsmId() int64 {
	if x != nil {
		return x.OsmId
	}
	return 0
}

func (x *NearestIndustrialSiteReply) GetDistM() float64 {
	if x != nil {
		return x.DistM
	}
	return 0
}

func (x *NearestIndustrialSiteReply) GetInside() bool {
	if x != nil {
		return x.Inside
	}
	return false
}

func (x *NearestIndustrialSiteReply) GetIndustrialType() string {
	if x != nil {
		return x.IndustrialType
	}
	return ""
}

type InsertLabelEventRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ClusterId           string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Source              string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // "gdelt" | "ai_worker"
	Label               string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Confidence          float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	MatchedArticleUrl   string                 `protobuf:"bytes,5,opt,name=matched_article_url,json=matchedArticleUrl,proto3" json:"matched_article_url,omitempty"`
	MatchedArticleTitle string                 `protobuf:"bytes,6,opt,name=matched_article_title,json=matchedArticleTitle,proto3" json:"matched_article_title,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InsertLabelEventRequest) Reset() {
	*x = InsertLabelEventRequest{}
	mi := &file_db_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertLabelEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLabelEventRequest) ProtoMessage() {}

func (x *InsertLabelEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLabelEventRequest.ProtoReflect.Descriptor instead.
func (*InsertLabelEventRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{35}
}

func (x *InsertLabelEventRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *InsertLabelEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *InsertLabelEventRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *InsertLabelEventRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *InsertLabelEventRequest) GetMatchedArticleUrl() string {
	if x != nil {
		return x.MatchedArticleUrl
	}
	return ""
}

func (x *InsertLabelEventRequest) GetMatchedArticleTitle() string {
	if x != nil {
		return x.MatchedArticleTitle
	}
	return ""
}

type InsertLabelEventReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertLabelEventReply) Reset() {
	*x = InsertLabelEventReply{}
	mi := &file_db_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertLabelEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLabelEventReply) ProtoMessage() {}

func (x *InsertLabelEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLabelEventReply.ProtoReflect.Descriptor instead.
func (*InsertLabelEventReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{36}
}

func (x *InsertLabelEventReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LabelEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId           string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Source              string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Label               string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Confidence          float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	MatchedArticleUrl   string                 `protobuf:"bytes,6,opt,name=matched_article_url,json=matchedArticleUrl,proto3" json:"matched_article_url,omitempty"`
	MatchedArticleTitle string                 `protobuf:"bytes,7,opt,name=matched_article_title,json=matchedArticleTitle,proto3" json:"matched_article_title,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LabelEvent) Reset() {
	*x = LabelEvent{}
	mi := &file_db_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelEvent) ProtoMessage() {}

func (x *LabelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelEvent.ProtoReflect.Descriptor instead.
func (*LabelEvent) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{37}
}

func (x *LabelEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LabelEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *LabelEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LabelEvent) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabelEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *LabelEvent) GetMatchedArticleUrl() string {
	if x != nil {
		return x.MatchedArticleUrl
	}
	return ""
}

func (x *LabelEvent) GetMatchedArticleTitle() string {
	if x != nil {
		return x.MatchedArticleTitle
	}
	return ""
}

func (x *LabelEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListLabelEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"` // "" = all clusters
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                         // 0 = server default (500), clamped to 5000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelEventsRequest) Reset() {
	*x = ListLabelEventsRequest{}
	mi := &file_db_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelEventsRequest) ProtoMessage() {}

func (x *ListLabelEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelEventsRequest.ProtoReflect.Descriptor instead.
func (*ListLabelEventsRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{38}
}

func (x *ListLabelEventsRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ListLabelEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLabelEventsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*LabelEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabelEventsReply) Reset() {
	*x = ListLabelEventsReply{}
	mi := &file_db_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabelEventsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabelEventsReply) ProtoMessage() {}

func (x *ListLabelEventsReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabelEventsReply.ProtoReflect.Descriptor instead.
func (*ListLabelEventsReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{39}
}

func (x *ListLabelEventsReply) GetEvents() []*LabelEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_db_proto protoreflect.FileDescriptor

const file_db_proto_rawDesc = "" +
	"\n" +
	"\bdb.proto\x12\x0emeridian.db.v1\"9\n" +
	"\x11UpsertUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"!\n" +
	"\x0fUpsertUserReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"(\n" +
	"\x10ListUsersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\",\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"<\n" +
	"\x0eListUsersReply\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.meridian.db.v1.UserR\x05users\"Y\n" +
	"\x18CreateChatSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"(\n" +
	"\x16CreateChatSessionReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"j\n" +
	"\vChatSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06pinned\x18\x03 \x01(\bR\x06pinned\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"2\n" +
	"\x17ListChatSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"P\n" +
	"\x15ListChatSessionsReply\x127\n" +
	"\bsessions\x18\x01 \x03(\v2\x1b.meridian.db.v1.ChatSessionR\bsessions\"Y\n" +
	"\x18RenameChatSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"(\n" +
	"\x16RenameChatSessionReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"C\n" +
	"\x18DeleteChatSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"(\n" +
	"\x16DeleteChatSessionReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Z\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x80\x01\n" +
	"\x18AppendChatMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"(\n" +
	"\x16AppendChatMessageReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"g\n" +
	"\x17ListChatMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"P\n" +
	"\x15ListChatMessagesReply\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.meridian.db.v1.ChatMessageR\bmessages\"\x8f\x05\n" +
	"\n" +
	"FirmsPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x19\n" +
	"\bacq_date\x18\x04 \x01(\tR\aacqDate\x12\x19\n" +
	"\bacq_time\x18\x05 \x01(\tR\aacqTime\x12\x1d\n" +
	"\n" +
	"bright_ti4\x18\x06 \x01(\x01R\tbrightTi4\x12\x1d\n" +
	"\n" +
	"bright_ti5\x18\a \x01(\x01R\tbrightTi5\x12\x10\n" +
	"\x03frp\x18\b \x01(\x01R\x03frp\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\tR\n" +
	"confidence\x12\x1c\n" +
	"\tsatellite\x18\n" +
	" \x01(\tR\tsatellite\x12\x1d\n" +
	"\n" +
	"bright_t31\x18\v \x01(\x01R\tbrightT31\x12\x12\n" +
	"\x04scan\x18\f \x01(\x01R\x04scan\x12\x14\n" +
	"\x05track\x18\r \x01(\x01R\x05track\x12\x1c\n" +
	"\tlandcover\x18\x0e \x01(\x05R\tlandcover\x12*\n" +
	"\x11dist_industrial_m\x18\x0f \x01(\x01R\x0fdistIndustrialM\x12+\n" +
	"\x11inside_industrial\x18\x10 \x01(\bR\x10insideIndustrial\x12\x15\n" +
	"\x06osm_id\x18\x11 \x01(\x03R\x05osmId\x12+\n" +
	"\x11persistence_score\x18\x12 \x01(\x01R\x10persistenceScore\x12'\n" +
	"\x0fpredicted_class\x18\x13 \x01(\tR\x0epredictedClass\x12'\n" +
	"\x0findustrial_prob\x18\x14 \x01(\x01R\x0eindustrialProb\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x15 \x01(\tR\tclusterId\"K\n" +
	"\x17UpsertFirmsPointRequest\x120\n" +
	"\x05point\x18\x01 \x01(\v2\x1a.meridian.db.v1.FirmsPointR\x05point\"'\n" +
	"\x15UpsertFirmsPointReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf1\x01\n" +
	"\x16ListFirmsPointsRequest\x12\x17\n" +
	"\amin_lat\x18\x01 \x01(\x01R\x06minLat\x12\x17\n" +
	"\amin_lon\x18\x02 \x01(\x01R\x06minLon\x12\x17\n" +
	"\amax_lat\x18\x03 \x01(\x01R\x06maxLat\x12\x17\n" +
	"\amax_lon\x18\x04 \x01(\x01R\x06maxLon\x12\x1b\n" +
	"\tdate_from\x18\x05 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x06 \x01(\tR\x06dateTo\x12'\n" +
	"\x0fpredicted_class\x18\a \x01(\tR\x0epredictedClass\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\"J\n" +
	"\x14ListFirmsPointsReply\x122\n" +
	"\x06points\x18\x01 \x03(\v2\x1a.meridian.db.v1.FirmsPointR\x06points\"\xcc\x02\n" +
	"%UpdateFirmsPointClassificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fpredicted_class\x18\x02 \x01(\tR\x0epredictedClass\x12'\n" +
	"\x0findustrial_prob\x18\x03 \x01(\x01R\x0eindustrialProb\x12+\n" +
	"\x11persistence_score\x18\x04 \x01(\x01R\x10persistenceScore\x12*\n" +
	"\x11dist_industrial_m\x18\x05 \x01(\x01R\x0fdistIndustrialM\x12+\n" +
	"\x11inside_industrial\x18\x06 \x01(\bR\x10insideIndustrial\x12\x1c\n" +
	"\tlandcover\x18\a \x01(\x05R\tlandcover\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\b \x01(\tR\tclusterId\"5\n" +
	"#UpdateFirmsPointClassificationReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xcc\x02\n" +
	"\x0eThermalCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcentroid_lat\x18\x02 \x01(\x01R\vcentroidLat\x12!\n" +
	"\fcentroid_lon\x18\x03 \x01(\x01R\vcentroidLon\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x17\n" +
	"\aavg_frp\x18\x05 \x01(\x01R\x06avgFrp\x12\x17\n" +
	"\amax_frp\x18\x06 \x01(\x01R\x06maxFrp\x12 \n" +
	"\vpersistence\x18\a \x01(\x01R\vpersistence\x12\x1d\n" +
	"\n" +
	"first_seen\x18\b \x01(\tR\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\t \x01(\tR\blastSeen\x12'\n" +
	"\x0fpredicted_class\x18\n" +
	" \x01(\tR\x0epredictedClass\x12\x15\n" +
	"\x06osm_id\x18\v \x01(\x03R\x05osmId\"W\n" +
	"\x1bUpsertThermalClusterRequest\x128\n" +
	"\acluster\x18\x01 \x01(\v2\x1e.meridian.db.v1.ThermalClusterR\acluster\"+\n" +
	"\x19UpsertThermalClusterReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x01\n" +
	"\x1aListThermalClustersRequest\x12\x17\n" +
	"\amin_lat\x18\x01 \x01(\x01R\x06minLat\x12\x17\n" +
	"\amin_lon\x18\x02 \x01(\x01R\x06minLon\x12\x17\n" +
	"\amax_lat\x18\x03 \x01(\x01R\x06maxLat\x12\x17\n" +
	"\amax_lon\x18\x04 \x01(\x01R\x06maxLon\"V\n" +
	"\x18ListThermalClustersReply\x12:\n" +
	"\bclusters\x18\x01 \x03(\v2\x1e.meridian.db.v1.ThermalClusterR\bclusters\"\xd4\x01\n" +
	"\x1bUpsertIndustrialSiteRequest\x12\x15\n" +
	"\x06osm_id\x18\x01 \x01(\x03R\x05osmId\x12!\n" +
	"\fcentroid_lat\x18\x02 \x01(\x01R\vcentroidLat\x12!\n" +
	"\fcentroid_lon\x18\x03 \x01(\x01R\vcentroidLon\x12'\n" +
	"\x0findustrial_type\x18\x04 \x01(\tR\x0eindustrialType\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1b\n" +
	"\ttags_json\x18\x06 \x01(\tR\btagsJson\"+\n" +
	"\x19UpsertIndustrialSiteReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"B\n" +
	"\x1cNearestIndustrialSiteRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"\xa1\x01\n" +
	"\x1aNearestIndustrialSiteReply\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x15\n" +
	"\x06osm_id\x18\x02 \x01(\x03R\x05osmId\x12\x15\n" +
	"\x06dist_m\x18\x03 \x01(\x01R\x05distM\x12\x16\n" +
	"\x06inside\x18\x04 \x01(\bR\x06inside\x12'\n" +
	"\x0findustrial_type\x18\x05 \x01(\tR\x0eindustrialType\"\xea\x01\n" +
	"\x17InsertLabelEventRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12.\n" +
	"\x13matched_article_url\x18\x05 \x01(\tR\x11matchedArticleUrl\x122\n" +
	"\x15matched_article_title\x18\x06 \x01(\tR\x13matchedArticleTitle\"'\n" +
	"\x15InsertLabelEventReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x02\n" +
	"\n" +
	"LabelEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12.\n" +
	"\x13matched_article_url\x18\x06 \x01(\tR\x11matchedArticleUrl\x122\n" +
	"\x15matched_article_title\x18\a \x01(\tR\x13matchedArticleTitle\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"M\n" +
	"\x16ListLabelEventsRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"J\n" +
	"\x14ListLabelEventsReply\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.meridian.db.v1.LabelEventR\x06events2\xe2\r\n" +
	"\x02Db\x12P\n" +
	"\n" +
	"UpsertUser\x12!.meridian.db.v1.UpsertUserRequest\x1a\x1f.meridian.db.v1.UpsertUserReply\x12M\n" +
	"\tListUsers\x12 .meridian.db.v1.ListUsersRequest\x1a\x1e.meridian.db.v1.ListUsersReply\x12e\n" +
	"\x11CreateChatSession\x12(.meridian.db.v1.CreateChatSessionRequest\x1a&.meridian.db.v1.CreateChatSessionReply\x12b\n" +
	"\x10ListChatSessions\x12'.meridian.db.v1.ListChatSessionsRequest\x1a%.meridian.db.v1.ListChatSessionsReply\x12e\n" +
	"\x11RenameChatSession\x12(.meridian.db.v1.RenameChatSessionRequest\x1a&.meridian.db.v1.RenameChatSessionReply\x12e\n" +
	"\x11DeleteChatSession\x12(.meridian.db.v1.DeleteChatSessionRequest\x1a&.meridian.db.v1.DeleteChatSessionReply\x12e\n" +
	"\x11AppendChatMessage\x12(.meridian.db.v1.AppendChatMessageRequest\x1a&.meridian.db.v1.AppendChatMessageReply\x12b\n" +
	"\x10ListChatMessages\x12'.meridian.db.v1.ListChatMessagesRequest\x1a%.meridian.db.v1.ListChatMessagesReply\x12b\n" +
	"\x10UpsertFirmsPoint\x12'.meridian.db.v1.UpsertFirmsPointRequest\x1a%.meridian.db.v1.UpsertFirmsPointReply\x12_\n" +
	"\x0fListFirmsPoints\x12&.meridian.db.v1.ListFirmsPointsRequest\x1a$.meridian.db.v1.ListFirmsPointsReply\x12\x8c\x01\n" +
	"\x1eUpdateFirmsPointClassification\x125.meridian.db.v1.UpdateFirmsPointClassificationRequest\x1a3.meridian.db.v1.UpdateFirmsPointClassificationReply\x12n\n" +
	"\x14UpsertThermalCluster\x12+.meridian.db.v1.UpsertThermalClusterRequest\x1a).meridian.db.v1.UpsertThermalClusterReply\x12k\n" +
	"\x13ListThermalClusters\x12*.meridian.db.v1.ListThermalClustersRequest\x1a(.meridian.db.v1.ListThermalClustersReply\x12n\n" +
	"\x14UpsertIndustrialSite\x12+.meridian.db.v1.UpsertIndustrialSiteRequest\x1a).meridian.db.v1.UpsertIndustrialSiteReply\x12q\n" +
	"\x15NearestIndustrialSite\x12,.meridian.db.v1.NearestIndustrialSiteRequest\x1a*.meridian.db.v1.NearestIndustrialSiteReply\x12b\n" +
	"\x10InsertLabelEvent\x12'.meridian.db.v1.InsertLabelEventRequest\x1a%.meridian.db.v1.InsertLabelEventReply\x12_\n" +
	"\x0fListLabelEvents\x12&.meridian.db.v1.ListLabelEventsRequest\x1a$.meridian.db.v1.ListLabelEventsReplyB8Z6github.com/idk4whatamiusing/meridian_stack/api/pb/dbpbb\x06proto3"

var (
	file_db_proto_rawDescOnce sync.Once
	file_db_proto_rawDescData []byte
)

func file_db_proto_rawDescGZIP() []byte {
	file_db_proto_rawDescOnce.Do(func() {
		file_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)))
	})
	return file_db_proto_rawDescData
}

var file_db_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_db_proto_goTypes = []any{
	(*UpsertUserRequest)(nil),                     // 0: meridian.db.v1.UpsertUserRequest
	(*UpsertUserReply)(nil),                       // 1: meridian.db.v1.UpsertUserReply
	(*ListUsersRequest)(nil),                      // 2: meridian.db.v1.ListUsersRequest
	(*User)(nil),                                  // 3: meridian.db.v1.User
	(*ListUsersReply)(nil),                        // 4: meridian.db.v1.ListUsersReply
	(*CreateChatSessionRequest)(nil),              // 5: meridian.db.v1.CreateChatSessionRequest
	(*CreateChatSessionReply)(nil),                // 6: meridian.db.v1.CreateChatSessionReply
	(*ChatSession)(nil),                           // 7: meridian.db.v1.ChatSession
	(*ListChatSessionsRequest)(nil),               // 8: meridian.db.v1.ListChatSessionsRequest
	(*ListChatSessionsReply)(nil),                 // 9: meridian.db.v1.ListChatSessionsReply
	(*RenameChatSessionRequest)(nil),              // 10: meridian.db.v1.RenameChatSessionRequest
	(*RenameChatSessionReply)(nil),                // 11: meridian.db.v1.RenameChatSessionReply
	(*DeleteChatSessionRequest)(nil),              // 12: meridian.db.v1.DeleteChatSessionRequest
	(*DeleteChatSessionReply)(nil),                // 13: meridian.db.v1.DeleteChatSessionReply
	(*ChatMessage)(nil),                           // 14: meridian.db.v1.ChatMessage
	(*AppendChatMessageRequest)(nil),              // 15: meridian.db.v1.AppendChatMessageRequest
	(*AppendChatMessageReply)(nil),                // 16: meridian.db.v1.AppendChatMessageReply
	(*ListChatMessagesRequest)(nil),               // 17: meridian.db.v1.ListChatMessagesRequest
	(*ListChatMessagesReply)(nil),                 // 18: meridian.db.v1.ListChatMessagesReply
	(*FirmsPoint)(nil),                            // 19: meridian.db.v1.FirmsPoint
	(*UpsertFirmsPointRequest)(nil),               // 20: meridian.db.v1.UpsertFirmsPointRequest
	(*UpsertFirmsPointReply)(nil),                 // 21: meridian.db.v1.UpsertFirmsPointReply
	(*ListFirmsPointsRequest)(nil),                // 22: meridian.db.v1.ListFirmsPointsRequest
	(*ListFirmsPointsReply)(nil),                  // 23: meridian.db.v1.ListFirmsPointsReply
	(*UpdateFirmsPointClassificationRequest)(nil), // 24: meridian.db.v1.UpdateFirmsPointClassificationRequest
	(*UpdateFirmsPointClassificationReply)(nil),   // 25: meridian.db.v1.UpdateFirmsPointClassificationReply
	(*ThermalCluster)(nil),                        // 26: meridian.db.v1.ThermalCluster
	(*UpsertThermalClusterRequest)(nil),           // 27: meridian.db.v1.UpsertThermalClusterRequest
	(*UpsertThermalClusterReply)(nil),             // 28: meridian.db.v1.UpsertThermalClusterReply
	(*ListThermalClustersRequest)(nil),            // 29: meridian.db.v1.ListThermalClustersRequest
	(*ListThermalClustersReply)(nil),              // 30: meridian.db.v1.ListThermalClustersReply
	(*UpsertIndustrialSiteRequest)(nil),           // 31: meridian.db.v1.UpsertIndustrialSiteRequest
	(*UpsertIndustrialSiteReply)(nil),             // 32: meridian.db.v1.UpsertIndustrialSiteReply
	(*NearestIndustrialSiteRequest)(nil),          // 33: meridian.db.v1.NearestIndustrialSiteRequest
	(*NearestIndustrialSiteReply)(nil),            // 34: meridian.db.v1.NearestIndustrialSiteReply
	(*InsertLabelEventRequest)(nil),               // 35: meridian.db.v1.InsertLabelEventRequest
	(*InsertLabelEventReply)(nil),                 // 36: meridian.db.v1.InsertLabelEventReply
	(*LabelEvent)(nil),                            // 37: meridian.db.v1.LabelEvent
	(*ListLabelEventsRequest)(nil),                // 38: meridian.db.v1.ListLabelEventsRequest
	(*ListLabelEventsReply)(nil),                  // 39: meridian.db.v1.ListLabelEventsReply
}
var file_db_proto_depIdxs = []int32{
	3,  // 0: meridian.db.v1.ListUsersReply.users:type_name -> meridian.db.v1.User
	7,  // 1: meridian.db.v1.ListChatSessionsReply.sessions:type_name -> meridian.db.v1.ChatSession
	14, // 2: meridian.db.v1.ListChatMessagesReply.messages:type_name -> meridian.db.v1.ChatMessage
	19, // 3: meridian.db.v1.UpsertFirmsPointRequest.point:type_name -> meridian.db.v1.FirmsPoint
	19, // 4: meridian.db.v1.ListFirmsPointsReply.points:type_name -> meridian.db.v1.FirmsPoint
	26, // 5: meridian.db.v1.UpsertThermalClusterRequest.cluster:type_name -> meridian.db.v1.ThermalCluster
	26, // 6: meridian.db.v1.ListThermalClustersReply.clusters:type_name -> meridian.db.v1.ThermalCluster
	37, // 7: meridian.db.v1.ListLabelEventsReply.events:type_name -> meridian.db.v1.LabelEvent
	0,  // 8: meridian.db.v1.Db.UpsertUser:input_type -> meridian.db.v1.UpsertUserRequest
	2,  // 9: meridian.db.v1.Db.ListUsers:input_type -> meridian.db.v1.ListUsersRequest
	5,  // 10: meridian.db.v1.Db.CreateChatSession:input_type -> meridian.db.v1.CreateChatSessionRequest
	8,  // 11: meridian.db.v1.Db.ListChatSessions:input_type -> meridian.db.v1.ListChatSessionsRequest
	10, // 12: meridian.db.v1.Db.RenameChatSession:input_type -> meridian.db.v1.RenameChatSessionRequest
	12, // 13: meridian.db.v1.Db.DeleteChatSession:input_type -> meridian.db.v1.DeleteChatSessionRequest
	15, // 14: meridian.db.v1.Db.AppendChatMessage:input_type -> meridian.db.v1.AppendChatMessageRequest
	17, // 15: meridian.db.v1.Db.ListChatMessages:input_type -> meridian.db.v1.ListChatMessagesRequest
	20, // 16: meridian.db.v1.Db.UpsertFirmsPoint:input_type -> meridian.db.v1.UpsertFirmsPointRequest
	22, // 17: meridian.db.v1.Db.ListFirmsPoints:input_type -> meridian.db.v1.ListFirmsPointsRequest
	24, // 18: meridian.db.v1.Db.UpdateFirmsPointClassification:input_type -> meridian.db.v1.UpdateFirmsPointClassificationRequest
	27, // 19: meridian.db.v1.Db.UpsertThermalCluster:input_type -> meridian.db.v1.UpsertThermalClusterRequest
	29, // 20: meridian.db.v1.Db.ListThermalClusters:input_type -> meridian.db.v1.ListThermalClustersRequest
	31, // 21: meridian.db.v1.Db.UpsertIndustrialSite:input_type -> meridian.db.v1.UpsertIndustrialSiteRequest
	33, // 22: meridian.db.v1.Db.NearestIndustrialSite:input_type -> meridian.db.v1.NearestIndustrialSiteRequest
	35, // 23: meridian.db.v1.Db.InsertLabelEvent:input_type -> meridian.db.v1.InsertLabelEventRequest
	38, // 24: meridian.db.v1.Db.ListLabelEvents:input_type -> meridian.db.v1.ListLabelEventsRequest
	1,  // 25: meridian.db.v1.Db.UpsertUser:output_type -> meridian.db.v1.UpsertUserReply
	4,  // 26: meridian.db.v1.Db.ListUsers:output_type -> meridian.db.v1.ListUsersReply
	6,  // 27: meridian.db.v1.Db.CreateChatSession:output_type -> meridian.db.v1.CreateChatSessionReply
	9,  // 28: meridian.db.v1.Db.ListChatSessions:output_type -> meridian.db.v1.ListChatSessionsReply
	11, // 29: meridian.db.v1.Db.RenameChatSession:output_type -> meridian.db.v1.RenameChatSessionReply
	13, // 30: meridian.db.v1.Db.DeleteChatSession:output_type -> meridian.db.v1.DeleteChatSessionReply
	16, // 31: meridian.db.v1.Db.AppendChatMessage:output_type -> meridian.db.v1.AppendChatMessageReply
	18, // 32: meridian.db.v1.Db.ListChatMessages:output_type -> meridian.db.v1.ListChatMessagesReply
	21, // 33: meridian.db.v1.Db.UpsertFirmsPoint:output_type -> meridian.db.v1.UpsertFirmsPointReply
	23, // 34: meridian.db.v1.Db.ListFirmsPoints:output_type -> meridian.db.v1.ListFirmsPointsReply
	25, // 35: meridian.db.v1.Db.UpdateFirmsPointClassification:output_type -> meridian.db.v1.UpdateFirmsPointClassificationReply
	28, // 36: meridian.db.v1.Db.UpsertThermalCluster:output_type -> meridian.db.v1.UpsertThermalClusterReply
	30, // 37: meridian.db.v1.Db.ListThermalClusters:output_type -> meridian.db.v1.ListThermalClustersReply
	32, // 38: meridian.db.v1.Db.UpsertIndustrialSite:output_type -> meridian.db.v1.UpsertIndustrialSiteReply
	34, // 39: meridian.db.v1.Db.NearestIndustrialSite:output_type -> meridian.db.v1.NearestIndustrialSiteReply
	36, // 40: meridian.db.v1.Db.InsertLabelEvent:output_type -> meridian.db.v1.InsertLabelEventReply
	39, // 41: meridian.db.v1.Db.ListLabelEvents:output_type -> meridian.db.v1.ListLabelEventsReply
	25, // [25:42] is the sub-list for method output_type
	8,  // [8:25] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_db_proto_init() }
func file_db_proto_init() {
	if File_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_proto_goTypes,
		DependencyIndexes: file_db_proto_depIdxs,
		MessageInfos:      file_db_proto_msgTypes,
	}.Build()
	File_db_proto = out.File
	file_db_proto_goTypes = nil
	file_db_proto_depIdxs = nil
}
