// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: ai.proto

package aipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	System        string                 `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	UseRag        bool                   `protobuf:"varint,3,opt,name=use_rag,json=useRag,proto3" json:"use_rag,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // per-user semantic cache isolation
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"` // cloudflare | bedrock | openai ("" = AI_PROVIDER default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *ChatRequest) GetUseRag() bool {
	if x != nil {
		return x.UseRag
	}
	return false
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *Source) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Source) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Source) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Source) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ChatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Sources       []*Source              `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Cached        bool                   `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReply) Reset() {
	*x = ChatReply{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReply) ProtoMessage() {}

func (x *ChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReply.ProtoReflect.Descriptor instead.
func (*ChatReply) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *ChatReply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatReply) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatReply) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ChatReply) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Sources       []*Source              `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"` // set on first chunk (RAG runs before streaming)
	Cached        bool                   `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ChatChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatChunk) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ChatChunk) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type SupportQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportQueryRequest) Reset() {
	*x = SupportQueryRequest{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportQueryRequest) ProtoMessage() {}

func (x *SupportQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportQueryRequest.ProtoReflect.Descriptor instead.
func (*SupportQueryRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *SupportQueryRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SupportQueryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SupportChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Sources       []*Source              `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Cached        bool                   `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportChunk) Reset() {
	*x = SupportChunk{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportChunk) ProtoMessage() {}

func (x *SupportChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportChunk.ProtoReflect.Descriptor instead.
func (*SupportChunk) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *SupportChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *SupportChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *SupportChunk) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *SupportChunk) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []string               `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`   // raw text documents to chunk+embed
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"` // "support" | "chat"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *IngestRequest) GetDocuments() []string {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *IngestRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type IngestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        int32                  `protobuf:"varint,1,opt,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestReply) Reset() {
	*x = IngestReply{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestReply) ProtoMessage() {}

func (x *IngestReply) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestReply.ProtoReflect.Descriptor instead.
func (*IngestReply) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *IngestReply) GetChunks() int32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *PredictRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PredictReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictReply) Reset() {
	*x = PredictReply{}
	mi := &file_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictReply) ProtoMessage() {}

func (x *PredictReply) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictReply.ProtoReflect.Descriptor instead.
func (*PredictReply) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{9}
}

func (x *PredictReply) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type ClassifyFirmsPointRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Lat        float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon        float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Frp        float64                `protobuf:"fixed64,3,opt,name=frp,proto3" json:"frp,omitempty"`
	BrightTi4  float64                `protobuf:"fixed64,4,opt,name=bright_ti4,json=brightTi4,proto3" json:"bright_ti4,omitempty"`
	BrightTi5  float64                `protobuf:"fixed64,5,opt,name=bright_ti5,json=brightTi5,proto3" json:"bright_ti5,omitempty"`
	Confidence string                 `protobuf:"bytes,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Satellite  string                 `protobuf:"bytes,7,opt,name=satellite,proto3" json:"satellite,omitempty"`
	// enrichment hints - unset means "not supplied by caller, let the ai
	// service look it up via db.NearestIndustrialSite (PostGIS)"; explicit
	// presence (proto3 optional) so a real 0m/false isn't confused with unset
	DistIndustrialM  *float64 `protobuf:"fixed64,8,opt,name=dist_industrial_m,json=distIndustrialM,proto3,oneof" json:"dist_industrial_m,omitempty"`
	InsideIndustrial *bool    `protobuf:"varint,9,opt,name=inside_industrial,json=insideIndustrial,proto3,oneof" json:"inside_industrial,omitempty"`
	Persistence      float64  `protobuf:"fixed64,10,opt,name=persistence,proto3" json:"persistence,omitempty"`  // 0..1
	Landcover        *int32   `protobuf:"varint,11,opt,name=landcover,proto3,oneof" json:"landcover,omitempty"` // unset -> Python sidecar auto-samples from ESA WorldCover
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClassifyFirmsPointRequest) Reset() {
	*x = ClassifyFirmsPointRequest{}
	mi := &file_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyFirmsPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyFirmsPointRequest) ProtoMessage() {}

func (x *ClassifyFirmsPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyFirmsPointRequest.ProtoReflect.Descriptor instead.
func (*ClassifyFirmsPointRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{10}
}

func (x *ClassifyFirmsPointRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *ClassifyFirmsPointRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *ClassifyFirmsPointRequest) GetFrp() float64 {
	if x != nil {
		return x.Frp
	}
	return 0
}

func (x *ClassifyFirmsPointRequest) GetBrightTi4() float64 {
	if x != nil {
		return x.BrightTi4
	}
	return 0
}

func (x *ClassifyFirmsPointRequest) GetBrightTi5() float64 {
	if x != nil {
		return x.BrightTi5
	}
	return 0
}

func (x *ClassifyFirmsPointRequest) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *ClassifyFirmsPointRequest) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *ClassifyFirmsPointRequest) GetDistIndustrialM() float64 {
	if x != nil && x.DistIndustrialM != nil {
		return *x.DistIndustrialM
	}
	return 0
}

func (x *ClassifyFirmsPointRequest) GetInsideIndustrial() bool {
	if x != nil && x.InsideIndustrial != nil {
		return *x.InsideIndustrial
	}
	return false
}

func (x *ClassifyFirmsPointRequest) GetPersistence() float64 {
	if x != nil {
		return x.Persistence
	}
	return 0
}

func (x *ClassifyFirmsPointRequest) GetLandcover() int32 {
	if x != nil && x.Landcover != nil {
		return *x.Landcover
	}
	return 0
}

type ClassifyFirmsPointReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PredictedClass string                 `protobuf:"bytes,1,opt,name=predicted_class,json=predictedClass,proto3" json:"predicted_class,omitempty"`
	IndustrialProb float64                `protobuf:"fixed64,2,opt,name=industrial_prob,json=industrialProb,proto3" json:"industrial_prob,omitempty"`
	Persistence    float64                `protobuf:"fixed64,3,opt,name=persistence,proto3" json:"persistence,omitempty"`
	Reasons        []string               `protobuf:"bytes,4,rep,name=reasons,proto3" json:"reasons,omitempty"`
	Landcover      *int32                 `protobuf:"varint,5,opt,name=landcover,proto3,oneof" json:"landcover,omitempty"` // value actually used (supplied or auto-sampled)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClassifyFirmsPointReply) Reset() {
	*x = ClassifyFirmsPointReply{}
	mi := &file_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyFirmsPointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyFirmsPointReply) ProtoMessage() {}

func (x *ClassifyFirmsPointReply) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyFirmsPointReply.ProtoReflect.Descriptor instead.
func (*ClassifyFirmsPointReply) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{11}
}

func (x *ClassifyFirmsPointReply) GetPredictedClass() string {
	if x != nil {
		return x.PredictedClass
	}
	return ""
}

func (x *ClassifyFirmsPointReply) GetIndustrialProb() float64 {
	if x != nil {
		return x.IndustrialProb
	}
	return 0
}

func (x *ClassifyFirmsPointReply) GetPersistence() float64 {
	if x != nil {
		return x.Persistence
	}
	return 0
}

func (x *ClassifyFirmsPointReply) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *ClassifyFirmsPointReply) GetLandcover() int32 {
	if x != nil && x.Landcover != nil {
		return *x.Landcover
	}
	return 0
}

type FirmsClusterPointIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Frp           float64                `protobuf:"fixed64,3,opt,name=frp,proto3" json:"frp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmsClusterPointIn) Reset() {
	*x = FirmsClusterPointIn{}
	mi := &file_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmsClusterPointIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmsClusterPointIn) ProtoMessage() {}

func (x *FirmsClusterPointIn) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmsClusterPointIn.ProtoReflect.Descriptor instead.
func (*FirmsClusterPointIn) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{12}
}

func (x *FirmsClusterPointIn) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *FirmsClusterPointIn) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *FirmsClusterPointIn) GetFrp() float64 {
	if x != nil {
		return x.Frp
	}
	return 0
}

type ClusterFirmsPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*FirmsClusterPointIn `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	EpsM          float64                `protobuf:"fixed64,2,opt,name=eps_m,json=epsM,proto3" json:"eps_m,omitempty"`                  // 0 = server default (1000)
	MinSamples    int32                  `protobuf:"varint,3,opt,name=min_samples,json=minSamples,proto3" json:"min_samples,omitempty"` // 0 = server default (3)
	WindowDays    int32                  `protobuf:"varint,4,opt,name=window_days,json=windowDays,proto3" json:"window_days,omitempty"` // 0 = server default (30)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterFirmsPointsRequest) Reset() {
	*x = ClusterFirmsPointsRequest{}
	mi := &file_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterFirmsPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterFirmsPointsRequest) ProtoMessage() {}

func (x *ClusterFirmsPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterFirmsPointsRequest.ProtoReflect.Descriptor instead.
func (*ClusterFirmsPointsRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{13}
}

func (x *ClusterFirmsPointsRequest) GetPoints() []*FirmsClusterPointIn {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *ClusterFirmsPointsRequest) GetEpsM() float64 {
	if x != nil {
		return x.EpsM
	}
	return 0
}

func (x *ClusterFirmsPointsRequest) GetMinSamples() int32 {
	if x != nil {
		return x.MinSamples
	}
	return 0
}

func (x *ClusterFirmsPointsRequest) GetWindowDays() int32 {
	if x != nil {
		return x.WindowDays
	}
	return 0
}

type FirmsClusterPointOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Cluster       int32                  `protobuf:"varint,3,opt,name=cluster,proto3" json:"cluster,omitempty"` // -1 = noise, unclustered
	Persistence   float64                `protobuf:"fixed64,4,opt,name=persistence,proto3" json:"persistence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmsClusterPointOut) Reset() {
	*x = FirmsClusterPointOut{}
	mi := &file_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmsClusterPointOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmsClusterPointOut) ProtoMessage() {}

func (x *FirmsClusterPointOut) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmsClusterPointOut.ProtoReflect.Descriptor instead.
func (*FirmsClusterPointOut) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{14}
}

func (x *FirmsClusterPointOut) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *FirmsClusterPointOut) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *FirmsClusterPointOut) GetCluster() int32 {
	if x != nil {
		return x.Cluster
	}
	return 0
}

func (x *FirmsClusterPointOut) GetPersistence() float64 {
	if x != nil {
		return x.Persistence
	}
	return 0
}

type ClusterFirmsPointsReply struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Clusters      []*FirmsClusterPointOut `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	NClusters     int32                   `protobuf:"varint,2,opt,name=n_clusters,json=nClusters,proto3" json:"n_clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterFirmsPointsReply) Reset() {
	*x = ClusterFirmsPointsReply{}
	mi := &file_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterFirmsPointsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterFirmsPointsReply) ProtoMessage() {}

func (x *ClusterFirmsPointsReply) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterFirmsPointsReply.ProtoReflect.Descriptor instead.
func (*ClusterFirmsPointsReply) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{15}
}

func (x *ClusterFirmsPointsReply) GetClusters() []*FirmsClusterPointOut {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ClusterFirmsPointsReply) GetNClusters() int32 {
	if x != nil {
		return x.NClusters
	}
	return 0
}

type IngestFirmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLat        float64                `protobuf:"fixed64,1,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MinLon        float64                `protobuf:"fixed64,2,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	MaxLat        float64                `protobuf:"fixed64,3,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	MaxLon        float64                `protobuf:"fixed64,4,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	DateFrom      string                 `protobuf:"bytes,5,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,6,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestFirmsRequest) Reset() {
	*x = IngestFirmsRequest{}
	mi := &file_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestFirmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestFirmsRequest) ProtoMessage() {}

func (x *IngestFirmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestFirmsRequest.ProtoReflect.Descriptor instead.
func (*IngestFirmsRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{16}
}

func (x *IngestFirmsRequest) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *IngestFirmsRequest) GetMinLon() float64 {
	if x != nil {
		return x.MinLon
	}
	return 0
}

func (x *IngestFirmsRequest) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

func (x *IngestFirmsRequest) GetMaxLon() float64 {
	if x != nil {
		return x.MaxLon
	}
	return 0
}

func (x *IngestFirmsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *IngestFirmsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type IngestFirmsReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	PointsIngested int32                  `protobuf:"varint,3,opt,name=points_ingested,json=pointsIngested,proto3" json:"points_ingested,omitempty"` // count of raw points fetched, enriched, classified and persisted
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IngestFirmsReply) Reset() {
	*x = IngestFirmsReply{}
	mi := &file_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestFirmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestFirmsReply) ProtoMessage() {}

func (x *IngestFirmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestFirmsReply.ProtoReflect.Descriptor instead.
func (*IngestFirmsReply) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{17}
}

func (x *IngestFirmsReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *IngestFirmsReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *IngestFirmsReply) GetPointsIngested() int32 {
	if x != nil {
		return x.PointsIngested
	}
	return 0
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x0emeridian.ai.v1\"\xac\x01\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06system\x18\x02 \x01(\tR\x06system\x12\x17\n" +
	"\ause_rag\x18\x03 \x01(\bR\x06useRag\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\"X\n" +
	"\x06Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\"\x81\x01\n" +
	"\tChatReply\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x120\n" +
	"\asources\x18\x03 \x03(\v2\x16.meridian.ai.v1.SourceR\asources\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\bR\x06cached\"\x7f\n" +
	"\tChatChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x120\n" +
	"\asources\x18\x03 \x03(\v2\x16.meridian.ai.v1.SourceR\asources\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\bR\x06cached\"H\n" +
	"\x13SupportQueryRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x82\x01\n" +
	"\fSupportChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x120\n" +
	"\asources\x18\x03 \x03(\v2\x16.meridian.ai.v1.SourceR\asources\x12\x16\n" +
	"\x06cached\x18\x04 \x01(\bR\x06cached\"M\n" +
	"\rIngestRequest\x12\x1c\n" +
	"\tdocuments\x18\x01 \x03(\tR\tdocuments\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"%\n" +
	"\vIngestReply\x12\x16\n" +
	"\x06chunks\x18\x01 \x01(\x05R\x06chunks\"$\n" +
	"\x0ePredictRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"$\n" +
	"\fPredictReply\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"\xaf\x03\n" +
	"\x19ClassifyFirmsPointRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03frp\x18\x03 \x01(\x01R\x03frp\x12\x1d\n" +
	"\n" +
	"bright_ti4\x18\x04 \x01(\x01R\tbrightTi4\x12\x1d\n" +
	"\n" +
	"bright_ti5\x18\x05 \x01(\x01R\tbrightTi5\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\tR\n" +
	"confidence\x12\x1c\n" +
	"\tsatellite\x18\a \x01(\tR\tsatellite\x12/\n" +
	"\x11dist_industrial_m\x18\b \x01(\x01H\x00R\x0fdistIndustrialM\x88\x01\x01\x120\n" +
	"\x11inside_industrial\x18\t \x01(\bH\x01R\x10insideIndustrial\x88\x01\x01\x12 \n" +
	"\vpersistence\x18\n" +
	" \x01(\x01R\vpersistence\x12!\n" +
	"\tlandcover\x18\v \x01(\x05H\x02R\tlandcover\x88\x01\x01B\x14\n" +
	"\x12_dist_industrial_mB\x14\n" +
	"\x12_inside_industrialB\f\n" +
	"\n" +
	"_landcover\"\xd8\x01\n" +
	"\x17ClassifyFirmsPointReply\x12'\n" +
	"\x0fpredicted_class\x18\x01 \x01(\tR\x0epredictedClass\x12'\n" +
	"\x0findustrial_prob\x18\x02 \x01(\x01R\x0eindustrialProb\x12 \n" +
	"\vpersistence\x18\x03 \x01(\x01R\vpersistence\x12\x18\n" +
	"\areasons\x18\x04 \x03(\tR\areasons\x12!\n" +
	"\tlandcover\x18\x05 \x01(\x05H\x00R\tlandcover\x88\x01\x01B\f\n" +
	"\n" +
	"_landcover\"K\n" +
	"\x13FirmsClusterPointIn\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03frp\x18\x03 \x01(\x01R\x03frp\"\xaf\x01\n" +
	"\x19ClusterFirmsPointsRequest\x12;\n" +
	"\x06points\x18\x01 \x03(\v2#.meridian.ai.v1.FirmsClusterPointInR\x06points\x12\x13\n" +
	"\x05eps_m\x18\x02 \x01(\x01R\x04epsM\x12\x1f\n" +
	"\vmin_samples\x18\x03 \x01(\x05R\n" +
	"minSamples\x12\x1f\n" +
	"\vwindow_days\x18\x04 \x01(\x05R\n" +
	"windowDays\"v\n" +
	"\x14FirmsClusterPointOut\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x18\n" +
	"\acluster\x18\x03 \x01(\x05R\acluster\x12 \n" +
	"\vpersistence\x18\x04 \x01(\x01R\vpersistence\"z\n" +
	"\x17ClusterFirmsPointsReply\x12@\n" +
	"\bclusters\x18\x01 \x03(\v2$.meridian.ai.v1.FirmsClusterPointOutR\bclusters\x12\x1d\n" +
	"\n" +
	"n_clusters\x18\x02 \x01(\x05R\tnClusters\"\xae\x01\n" +
	"\x12IngestFirmsRequest\x12\x17\n" +
	"\amin_lat\x18\x01 \x01(\x01R\x06minLat\x12\x17\n" +
	"\amin_lon\x18\x02 \x01(\x01R\x06minLon\x12\x17\n" +
	"\amax_lat\x18\x03 \x01(\x01R\x06maxLat\x12\x17\n" +
	"\amax_lon\x18\x04 \x01(\x01R\x06maxLon\x12\x1b\n" +
	"\tdate_from\x18\x05 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x06 \x01(\tR\x06dateTo\"a\n" +
	"\x10IngestFirmsReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x0fpoints_ingested\x18\x03 \x01(\x05R\x0epointsIngested2\x99\x05\n" +
	"\x02Ai\x12>\n" +
	"\x04Chat\x12\x1b.meridian.ai.v1.ChatRequest\x1a\x19.meridian.ai.v1.ChatReply\x12F\n" +
	"\n" +
	"ChatStream\x12\x1b.meridian.ai.v1.ChatRequest\x1a\x19.meridian.ai.v1.ChatChunk0\x01\x12S\n" +
	"\fSupportQuery\x12#.meridian.ai.v1.SupportQueryRequest\x1a\x1c.meridian.ai.v1.SupportChunk0\x01\x12D\n" +
	"\x06Ingest\x12\x1d.meridian.ai.v1.IngestRequest\x1a\x1b.meridian.ai.v1.IngestReply\x12G\n" +
	"\aPredict\x12\x1e.meridian.ai.v1.PredictRequest\x1a\x1c.meridian.ai.v1.PredictReply\x12h\n" +
	"\x12ClassifyFirmsPoint\x12).meridian.ai.v1.ClassifyFirmsPointRequest\x1a'.meridian.ai.v1.ClassifyFirmsPointReply\x12h\n" +
	"\x12ClusterFirmsPoints\x12).meridian.ai.v1.ClusterFirmsPointsRequest\x1a'.meridian.ai.v1.ClusterFirmsPointsReply\x12S\n" +
	"\vIngestFirms\x12\".meridian.ai.v1.IngestFirmsRequest\x1a .meridian.ai.v1.IngestFirmsReplyB8Z6github.com/idk4whatamiusing/meridian_stack/api/pb/aipbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ai_proto_goTypes = []any{
	(*ChatRequest)(nil),               // 0: meridian.ai.v1.ChatRequest
	(*Source)(nil),                    // 1: meridian.ai.v1.Source
	(*ChatReply)(nil),                 // 2: meridian.ai.v1.ChatReply
	(*ChatChunk)(nil),                 // 3: meridian.ai.v1.ChatChunk
	(*SupportQueryRequest)(nil),       // 4: meridian.ai.v1.SupportQueryRequest
	(*SupportChunk)(nil),              // 5: meridian.ai.v1.SupportChunk
	(*IngestRequest)(nil),             // 6: meridian.ai.v1.IngestRequest
	(*IngestReply)(nil),               // 7: meridian.ai.v1.IngestReply
	(*PredictRequest)(nil),            // 8: meridian.ai.v1.PredictRequest
	(*PredictReply)(nil),              // 9: meridian.ai.v1.PredictReply
	(*ClassifyFirmsPointRequest)(nil), // 10: meridian.ai.v1.ClassifyFirmsPointRequest
	(*ClassifyFirmsPointReply)(nil),   // 11: meridian.ai.v1.ClassifyFirmsPointReply
	(*FirmsClusterPointIn)(nil),       // 12: meridian.ai.v1.FirmsClusterPointIn
	(*ClusterFirmsPointsRequest)(nil), // 13: meridian.ai.v1.ClusterFirmsPointsRequest
	(*FirmsClusterPointOut)(nil),      // 14: meridian.ai.v1.FirmsClusterPointOut
	(*ClusterFirmsPointsReply)(nil),   // 15: meridian.ai.v1.ClusterFirmsPointsReply
	(*IngestFirmsRequest)(nil),        // 16: meridian.ai.v1.IngestFirmsRequest
	(*IngestFirmsReply)(nil),          // 17: meridian.ai.v1.IngestFirmsReply
}
var file_ai_proto_depIdxs = []int32{
	1,  // 0: meridian.ai.v1.ChatReply.sources:type_name -> meridian.ai.v1.Source
	1,  // 1: meridian.ai.v1.ChatChunk.sources:type_name -> meridian.ai.v1.Source
	1,  // 2: meridian.ai.v1.SupportChunk.sources:type_name -> meridian.ai.v1.Source
	12, // 3: meridian.ai.v1.ClusterFirmsPointsRequest.points:type_name -> meridian.ai.v1.FirmsClusterPointIn
	14, // 4: meridian.ai.v1.ClusterFirmsPointsReply.clusters:type_name -> meridian.ai.v1.FirmsClusterPointOut
	0,  // 5: meridian.ai.v1.Ai.Chat:input_type -> meridian.ai.v1.ChatRequest
	0,  // 6: meridian.ai.v1.Ai.ChatStream:input_type -> meridian.ai.v1.ChatRequest
	4,  // 7: meridian.ai.v1.Ai.SupportQuery:input_type -> meridian.ai.v1.SupportQueryRequest
	6,  // 8: meridian.ai.v1.Ai.Ingest:input_type -> meridian.ai.v1.IngestRequest
	8,  // 9: meridian.ai.v1.Ai.Predict:input_type -> meridian.ai.v1.PredictRequest
	10, // 10: meridian.ai.v1.Ai.ClassifyFirmsPoint:input_type -> meridian.ai.v1.ClassifyFirmsPointRequest
	13, // 11: meridian.ai.v1.Ai.ClusterFirmsPoints:input_type -> meridian.ai.v1.ClusterFirmsPointsRequest
	16, // 12: meridian.ai.v1.Ai.IngestFirms:input_type -> meridian.ai.v1.IngestFirmsRequest
	2,  // 13: meridian.ai.v1.Ai.Chat:output_type -> meridian.ai.v1.ChatReply
	3,  // 14: meridian.ai.v1.Ai.ChatStream:output_type -> meridian.ai.v1.ChatChunk
	5,  // 15: meridian.ai.v1.Ai.SupportQuery:output_type -> meridian.ai.v1.SupportChunk
	7,  // 16: meridian.ai.v1.Ai.Ingest:output_type -> meridian.ai.v1.IngestReply
	9,  // 17: meridian.ai.v1.Ai.Predict:output_type -> meridian.ai.v1.PredictReply
	11, // 18: meridian.ai.v1.Ai.ClassifyFirmsPoint:output_type -> meridian.ai.v1.ClassifyFirmsPointReply
	15, // 19: meridian.ai.v1.Ai.ClusterFirmsPoints:output_type -> meridian.ai.v1.ClusterFirmsPointsReply
	17, // 20: meridian.ai.v1.Ai.IngestFirms:output_type -> meridian.ai.v1.IngestFirmsReply
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	file_ai_proto_msgTypes[10].OneofWrappers = []any{}
	file_ai_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
