#!/usr/bin/env node
// Single source .env -> gateway/.dev.vars derivation
// Reads root .env, writes gateway/.dev.vars (gitignored)
// No secrets hardcoded anywhere

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const envPath = join(root, ".env");
const outPath = join(root, "gateway", ".dev.vars");

if (!existsSync(envPath)) {
  console.error(`.env not found at ${envPath} — copy .env.example to .env and fill secrets`);
  process.exit(1);
}

const raw = readFileSync(envPath, "utf8");

// minimal dotenv parse (no deps)
const env = {};
for (const line of raw.split("\n")) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const idx = trimmed.indexOf("=");
  if (idx === -1) continue;
  const k = trimmed.slice(0, idx).trim();
  let v = trimmed.slice(idx + 1).trim();
  // strip quotes
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
  // resolve ${VAR} inside value using already parsed env
  v = v.replace(/\$\{([^}]+)\}/g, (_, name) => env[name] ?? process.env[name] ?? "");
  env[k] = v;
}

// Derive worker vars from root .env — never hardcode
const domain = env.DOMAIN || "";
const apiOrigin = env.API_ORIGIN || (domain && domain !== "YOUR_PUBLIC_IP.sslip.io" ? `https://api.${domain}` : "http://localhost:8000");
const lines = [
  `# auto-generated by scripts/sync-env.mjs from ../.env — do not edit manually`,
  `# single source is root .env (gitignored)`,
  `API_ORIGIN=${apiOrigin}`,
  `BACKEND_SECRET=${env.BACKEND_SECRET || "change-me"}`,
  `SESSION_TTL=${env.SESSION_TTL || "604800"}`,
  `GOOGLE_CLIENT_ID=${env.GOOGLE_CLIENT_ID || ""}`,
  `GOOGLE_CLIENT_SECRET=${env.GOOGLE_CLIENT_SECRET || ""}`,
];

writeFileSync(outPath, lines.join("\n") + "\n");
console.log(`wrote ${outPath} (derived from .env)`);
console.log(`  API_ORIGIN=${apiOrigin}`);
console.log(`  BACKEND_SECRET=${env.BACKEND_SECRET ? "***" : "change-me"}`);
console.log(`  GOOGLE_CLIENT_ID=${env.GOOGLE_CLIENT_ID ? env.GOOGLE_CLIENT_ID.slice(0, 8) + "...": "(empty)"}`);
