// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type BoundingBox struct {
	MinLat float64 `json:"minLat"`
	MinLon float64 `json:"minLon"`
	MaxLat float64 `json:"maxLat"`
	MaxLon float64 `json:"maxLon"`
}

type ChatChunk struct {
	Delta   string    `json:"delta"`
	Done    bool      `json:"done"`
	Sources []*Source `json:"sources"`
	Cached  bool      `json:"cached"`
}

type ChatReply struct {
	Reply   string    `json:"reply"`
	Model   string    `json:"model"`
	Sources []*Source `json:"sources"`
	Cached  bool      `json:"cached"`
}

type ChatSession struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Pinned    bool   `json:"pinned"`
	UpdatedAt string `json:"updatedAt"`
}

type ClassifyFirmsPointInput struct {
	Lat              float64  `json:"lat"`
	Lon              float64  `json:"lon"`
	Frp              *float64 `json:"frp,omitempty"`
	BrightTi4        *float64 `json:"brightTi4,omitempty"`
	BrightTi5        *float64 `json:"brightTi5,omitempty"`
	Confidence       *string  `json:"confidence,omitempty"`
	Satellite        *string  `json:"satellite,omitempty"`
	DistIndustrialM  *float64 `json:"distIndustrialM,omitempty"`
	InsideIndustrial *bool    `json:"insideIndustrial,omitempty"`
	Persistence      *float64 `json:"persistence,omitempty"`
	Landcover        *int     `json:"landcover,omitempty"`
}

type FirmsClassification struct {
	PredictedClass string   `json:"predictedClass"`
	IndustrialProb float64  `json:"industrialProb"`
	Persistence    float64  `json:"persistence"`
	Reasons        []string `json:"reasons"`
}

type FirmsPoint struct {
	ID               string  `json:"id"`
	Latitude         float64 `json:"latitude"`
	Longitude        float64 `json:"longitude"`
	AcqDate          string  `json:"acqDate"`
	AcqTime          string  `json:"acqTime"`
	BrightTi4        float64 `json:"brightTi4"`
	BrightTi5        float64 `json:"brightTi5"`
	Frp              float64 `json:"frp"`
	Confidence       string  `json:"confidence"`
	Satellite        string  `json:"satellite"`
	Landcover        int     `json:"landcover"`
	DistIndustrialM  float64 `json:"distIndustrialM"`
	InsideIndustrial bool    `json:"insideIndustrial"`
	OsmID            string  `json:"osmId"`
	PersistenceScore float64 `json:"persistenceScore"`
	PredictedClass   string  `json:"predictedClass"`
	IndustrialProb   float64 `json:"industrialProb"`
	ClusterID        *string `json:"clusterId,omitempty"`
}

type FirmsPointInput struct {
	ID         string   `json:"id"`
	Latitude   float64  `json:"latitude"`
	Longitude  float64  `json:"longitude"`
	AcqDate    string   `json:"acqDate"`
	AcqTime    *string  `json:"acqTime,omitempty"`
	BrightTi4  float64  `json:"brightTi4"`
	BrightTi5  float64  `json:"brightTi5"`
	Frp        float64  `json:"frp"`
	Confidence string   `json:"confidence"`
	Satellite  string   `json:"satellite"`
	BrightT31  *float64 `json:"brightT31,omitempty"`
	Scan       *float64 `json:"scan,omitempty"`
	Track      *float64 `json:"track,omitempty"`
}

type Message struct {
	Role      string `json:"role"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Source struct {
	ID    string  `json:"id"`
	Title *string `json:"title,omitempty"`
	Text  string  `json:"text"`
	Score float64 `json:"score"`
}

type Subscription struct {
}

type ThermalCluster struct {
	ID             string  `json:"id"`
	CentroidLat    float64 `json:"centroidLat"`
	CentroidLon    float64 `json:"centroidLon"`
	Count          int     `json:"count"`
	AvgFrp         float64 `json:"avgFrp"`
	MaxFrp         float64 `json:"maxFrp"`
	Persistence    float64 `json:"persistence"`
	FirstSeen      string  `json:"firstSeen"`
	LastSeen       string  `json:"lastSeen"`
	PredictedClass string  `json:"predictedClass"`
	OsmID          *string `json:"osmId,omitempty"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
